name: Git Bundle Checkout
description: Seeds the Buildkite checkout directory from a GCS-hosted git bundle to speed up checkout
author: Hivebrite
requirements:
  - gcloud
  - git
configuration:
  properties:
    gcs_uri:
      type: string
  required:
    - gcs_uri
